### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by 1M4Z3N** [HatBashBR/HatCloud#19]
```
hatcloud.rb:84:in `+': no implicit conversion of nil into String (TypeError)
	from hatcloud.rb:84:in `<main>'
```

**Comment by mateeuslinno** [comment]
What is your target ? send me please.

**Comment by 1M4Z3N** [comment]
[https://i.imgur.com/Lq6Xeyu.png](url)

**Comment by mateeuslinno** [comment]
Hi @1M4Z3N do you can send more details ? You cand send e-mail.. My e-mail is: dctoralves@protonmail.ch.. But if you are try bypass of IPV6..  The script does not support yet.. Sorry..

**Comment by mateeuslinno** [comment]
208.52.182.215

**Comment by 1M4Z3N** [comment]
thankyou so much
