### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by hexben** [HatBashBR/HatCloud#27]
Hi,

After identifying the domain, I got this error:

Fatail Erro !
[+] Site analysis: targetsite.com
[+] CloudFlare IP is xxx.xxx.xxx.xxx
[+] Real IP is
Traceback (most recent call last):
        8: from C:/Users/admin/Documents/HatCloud-master/hatcloud.rb:87:in `<main>'
        7: from C:/Ruby25/lib/ruby/2.5.0/open-uri.rb:743:in `read'
        6: from C:/Ruby25/lib/ruby/2.5.0/open-uri.rb:735:in `open'
        5: from C:/Ruby25/lib/ruby/2.5.0/open-uri.rb:165:in `open_uri'
        4: from C:/Ruby25/lib/ruby/2.5.0/open-uri.rb:224:in `open_loop'
        3: from C:/Ruby25/lib/ruby/2.5.0/open-uri.rb:224:in `catch'
        2: from C:/Ruby25/lib/ruby/2.5.0/open-uri.rb:226:in `block in open_loop'

        1: from C:/Ruby25/lib/ruby/2.5.0/open-uri.rb:755:in `buffer_open'
C:/Ruby25/lib/ruby/2.5.0/open-uri.rb:377:in `open_http': 404 Not Found (OpenURI::HTTPError)

I replaced the old URI with a new one : http://www.crimeflare.org:82/cgi-bin/cfsearch.cgi

but this time I got 

[-] No valid address - are you sure this is a CloudFlare protected domain?

Your help will be appreciated.

Thanks
Ben

**Comment by Kaiseroni** [comment]
I agree with hexben , I have also the same error here even after i replaced the URL.

**Comment by visions** [comment]
It is an issue with crimeflare.com.  Posting the form directly on crimeflare.com results in the same error.

**Comment by asadglobalshopaholics** [comment]
same issue i'm facing right now...is there any solution ???
