### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by osintcoruja** [HatBashBR/HatCloud#31]
Ao rodar o programa aparece a seguinte mensagem:

       8: from hatcloud.rb:87:in `<main>'
        7: from /usr/lib/ruby/2.7.0/open-uri.rb:752:in `read'
        6: from /usr/lib/ruby/2.7.0/open-uri.rb:744:in `open'
        5: from /usr/lib/ruby/2.7.0/open-uri.rb:174:in `open_uri'
        4: from /usr/lib/ruby/2.7.0/open-uri.rb:233:in `open_loop'
        3: from /usr/lib/ruby/2.7.0/open-uri.rb:233:in `catch'
        2: from /usr/lib/ruby/2.7.0/open-uri.rb:235:in `block in open_loop'
        1: from /usr/lib/ruby/2.7.0/open-uri.rb:764:in `buffer_open'
/usr/lib/ruby/2.7.0/open-uri.rb:387:in `open_http': 404 Not Found (OpenURI::HTTPError)

**Comment by MiChaelinzo** [comment]
alterando a carga útil hatcloud.rb na linha 64 substituindo o link crimeflare.us:82/cgi-bin/cfsearch.cgi para crimeflare.org:82/cgi-bin/cfsearch.cgi
e mudar .us em .org corrigiu o problema
mas você ainda terá
[-] Nenhum endereço válido - você tem certeza que este é um domínio protegido por CloudFlare?

**Comment by 3t3rium** [comment]
@MiChaelinzo thats a solution for the problem described before, but once you modify that file another error shows up


[-] No valid address - are you sure this is a CloudFlare protected domain?

i've tried with different domains and always the output is the same, unless the target used is discordapp.com
